### ISSUE TITLE
15 min surplus data?

### ISSUE THREAD

**Issue by sshoecraft** [grahamwetzler/smart-meter-texas#133]
Graham, do you have any examples of using the 15 min data?   I currently pull from python (directly, using requests) but only allows me to login once/hour.

I see your update for "Adding in 15 minute read-data for Surplus Generation."  The current plan that i'm on only pays using the RTSS prices ... is that what your doing?  If so, do you have an example of how to pull the 15 min data AND bring in the 15 min RT price?

https://www.ercot.com/content/cdr/html/real_time_spp.html

If, not any info on how to pull the surplus gen every 15 min would be great

**Comment by grahamwetzler** [comment]
Sorry, I don't. Also, as far as I'm aware this package isn't able to connect to SMT at the moment due to some weird TLS issues on their end.
