### ISSUE TITLE
SMT Fails to Authenticate

### ISSUE THREAD

**Issue by grahamwetzler** [grahamwetzler/smart-meter-texas#144]
Originally reported [here](https://github.com/home-assistant/core/issues/101166), the library is no longer working. Seems like something changed with authentication.

The authentication endpoint now has the www subdomain, but updating that in the code still doesn't work. It just stops at `Requesting login token`

```
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:smart_meter_texas:Found CA Issuers URI value: http://r3.i.lencr.org/
DEBUG:smart_meter_texas:Loaded certificate file into SSL Context
Authenticating...
DEBUG:smart_meter_texas:Requesting login token
```

**Comment by jimmyhon** [comment]
The `www` subdomain goes through the Akamai CDN and the `/api/user/authenticate` route is protected by the Akamai Bot Manager.

https://www.akamai.com/products/bot-manager

The browser needs to run Akamai's Javascript Challenge and set browser cookies.

https://www.zenrows.com/blog/bypass-akamai#what-is-bot-detection-software.

The code bypassed Akamai by going straight to smartmetertexas.com.

**Comment by chutson92** [comment]
Any updates or a workaround on this?

**Comment by shbatm** [comment]
I have a rough working script here: https://gist.github.com/shbatm/d10a703cc3e3817e9bf53fec9eae52a6 just to prove you could still access this via script with their V3 update. Still haven't been able to integrate it back into this yet, but I have learned:

1. The authentication url changed to `/commonapi/user/authenticate`
2. It appears a `user-agent` must be set, but looks like you don't need the cookies.
3. Must be a `HTTP/2` connection.

**Comment by scadaguru** [comment]
> I have a rough working script here: https://gist.github.com/shbatm/d10a703cc3e3817e9bf53fec9eae52a6 just to prove you could still access this via script with their V3 update. Still haven't been able to integrate it back into this yet, but I have learned:
> 
> 1. The authentication url changed to `/commonapi/user/authenticate`
> 2. It appears a `user-agent` must be set, but looks like you don't need the cookies.
> 3. Must be a `HTTP/2` connection.
Excellent job!
I got working my docker app after making the changes you suggested! thank you so much!
Now, let's see how long it runs before "they" make breaking changes!
Thanks

**Comment by grahamwetzler** [comment]
Thanks @shbatm. Unfortunately `aiohttp` doesn't seem to support http/2, so this may need to be refactored using something like `httpx`.

**Comment by kdeyev** [comment]
@grahamwetzler Please take a look at [my PR](https://github.com/grahamwetzler/smart-meter-texas/pull/146).
I was able to get it working. Looking forward to getting the HA integration fixed.
